[#disciplinarni-rizeni]
== DISCIPLINÁRNÍ ŘÍZENÍ

[#disciplinarni-rizeni-uvod]
=== ÚVOD

. [[dru-1,{counter:dru}]]Hlavní rozhodčí má celkovou pravomoc nad činnostmi a rozhodnutími týkajícími se <<#soutezni-prostor,soutěžního prostoru>>.

. [[dru-2,{counter:dru}]]Hlavní rozhodčí má oprávnění přijmout následující opatření v případě porušení pravidel soutěže, co se týče nekázně kteréhokoliv <<#clenove-tymu,člena týmu>>:
.. [[drs-a,{counter:drsa:a}]]neoficiální, slovní napomenutí;
.. [[drs-b,{counter:drsa}]]oficiální napomenutí doprovázené ukázáním žluté karty.

. V nejbližší vhodné chvíli po vydání žluté nebo červené karty musí Hlavní rozhodčí:
.. předložit písemné vyjádření týkající se provinění <<#manazer-tymu,vedoucímu týmu>> soutěžícího (nebo danému soutěžícímu v případě nepřítomnosti vedoucího týmu) a toho, zdali Hlavní rozhodčí hodlá danou záležitost předat k posouzení Disciplinární komisi ČHS.
.. pokud bude přestupek dále řešen Disciplinární komisí ČHS musí dále bez zbytečného prodlení předat Disciplinární komisi ČHS: kopii tohoto písemného vyjádření společně s detailní zprávou týkající se daného přestupku proti pravidlům, jakýmkoliv důkazním materiálem a jakýmkoliv návrhem dalšího postupu ohledně zvážení případných dalších postihů. 

. Složení a způsob práce disciplinární komise popisují příslušné dokumenty ČHS – Stanovy ČHS a Disciplinární řád ČHS.

[#zluta-karta]
=== ŽLUTÁ KARTA
. Žlutá karta může být v souladu s výše zmíněným článkem <<#disciplinarni-rizeni-uvod>>.<<#dru-2>>.<<#drs-b>> udělena za jakékoliv z následujících porušení pravidel:
.. za porušení kterýmkoliv členem týmu v soutěžním prostoru:
... nesportovní chování relativně malé povahy
... použití obscénního nebo urážlivého jazyka nebo chování relativně mírné povahy
.. vzhledem k pokynům oficiálního činovníka ČHS, za neuposlechnutí takových pokynů jako
... nepřiměřené zdržení při návratu do izolace, když k tomu dá Hlavní rozhodčí pokyn;
... nepřiměřené zdržení mezi opuštěním přípravné zóny a příchodem do soutěžní zóny, když je k tomu dán pokyn;
... neschopnost odstartovat v souladu s pokyny Hlavního rozhodčího
.. Vzhledem k vybavení a slavnostním aktům, za:
... porušení pravidel a nařízení ČHS ohledně vybavení a oblečení platných pro danou soutěž;
... nenošení dresu poskytnutého pořadatelem soutěže;
... nenošení startovního čísla poskytnutého pořadatelem soutěže;
... neúčast soutěžících na zahajovacím ceremoniálu;
... neúčast tří nejlepších finalistů při udílení cen;

. <<#oficialni-doprovod, Oficiální doprovod týmu>> po obdržení žluté karty nesmí mít povolen přístup do jakékoliv zóny soutěžního prostoru během konání soutěže, z důvodu prospěchu týmu.

=== DISKVALIFIKACE (DSQ)
. Hlavní rozhodčí je oprávněný diskvalifikovat libovolného <<#clenove-tymu,člena týmu>>. 
. Následující porušení pravidel budou potrestána udělením červené karty a okamžitou diskvalifikací soutěžícího ze soutěže a mohou být podstoupena disciplinární komisi:

.. použití neschváleného vybavení;
.. nepovolené použití jakéhokoliv způsobu komunikace v rámci soutěžního prostoru.
.. s ohledem na každé kolo, které probíhá za <<#podminky-izolace,podmínek izolace>>, získáním nebo poskytnutím informací jinak, než umožňují podmínky izolace včetně, ale ne omezeno jen na
... od libovolné osoby mimo soutěžní prostor
... od libovolné osoby, která již absolvovala příslušnou cestu/boulder

+
Aby se předešlo pochybnostem, v soutěžních kolech, kde se podmínky izolace neaplikují, mohou soutěžící získávat informace od jiných členů týmu, kteří jsou mimo soutěžní prostor. a to jak před pokusem, tak i během jejich pokusu.

=== Diskvalifikace za chování (DQB)
. Hlavní rozhodčí je oprávněný diskvalifikovat za chování libovolného <<#clenove-tymu,člena týmu>>. Jakákoliv diskvalifikace za chování bude potrestána udělením červené karty a bude postoupena Disciplinární komisi ČHS. A dále okamžitou diskvalifikací soutěžícího ze všech soutěží dané <<#soutez,Soutěže>>. 

. Následující záležitosti budou mít za následek okamžitou diskvalifikaci za chování:
.. nepodvolení se pokynům rozhodčích, pořadatelů nebo soutěžních činitelů ČHS, pokud se tak děje v soutěžním prostoru
.. odmítnutí se podrobit soutěžnímu testu link:https://cs.wikipedia.org/wiki/Index_t%C4%9Blesn%C3%A9_hmotnosti[Indexu tělesné hmotnosti (BMI)] na pokyn Hlavního rozhodčího
.. rozptylování jakéhokoliv sportovce nebo překážení sportovci, který se připravuje nebo již leze svůj pokus na cestě;
.. odmítnutí podřídit se nařízením o reklamě platným pro oblečení a vybavení;
.. získání dvou žlutých karet stejnou osobou během jedné soutěže
.. Nesportovní chování nebo jiná vážná výtržnost v průběhu soutěže;
.. Hrubé, výhružné nebo násilné chování ve vztahu k soutěžním činitelům ČHS, pořadatelům, členům týmů (včetně sportovců) nebo jakékoliv jiné osobě.

. Přestupky spáchané sportovcem nebo členem týmu mimo soutěžní prostor, ale ve veřejné aréně, v dějišti soutěže nebo v ubytovacích nebo jiných zařízeních se soutěží spjatých:
.. značně nesportovní chování nebo jiná vážná výtržnost;
.. hrubé, výhružné nebo násilné chování ve vztahu k soutěžním činitelům ČHS, pořadatelům, členům týmů (včetně sportovců) nebo jakékoliv jiné osobě.

. Kroky, které následují v případě postoupení přestupku Disciplinární komisi ČHS, jsou stanoveny Disciplinárním řádem ČHS.

=== DŮSLEDKY DISCIPLINÁRNÍHO POSTIHU
. Soutěžící, který je diskvalifikován nebo je diskvalifikován pro chování nebude hodnocen na žádné soutěži, která tvoří společnou jednu soutěž.
. Udělení třetí žluté karty v jedné sezóně bude mít za následek jeden z následujících postihů:
.. [[ddp-1,{counter:ddp:a}.]]V případě, že je soutěžící již přihlášen pro nadcházející soutěž ČHS započítávající se do průběžného rankingu, nebude soutěžící způsobilý se této soutěže zúčastnit;
.. [[ddp-2,{counter:ddp}.]]Není-li použitelná možnost <<#ddp-1>>, pak soutěžící nebude způsobilý zúčastnit se další soutěže ČHS započítávající se do průběžného rankingu ve stejné disciplíně, jako v té, kde soutěžící obdržel třetí žlutou kartu.

[#ostatni-osoby]
=== OSTATNÍ OSOBY

. Hlavní rozhodčí je oprávněn vyzvat jakékoliv osoby, které jednají v rozporu s pravidly, k okamžitému opuštění soutěžního prostoru a je-li to nutné, může pozastavit veškerou soutěžní činnost do doby, než bude jeho požadavku vyhověno.