[#obtiznost]
== LEZENÍ NA OBTÍŽNOST

[#obtiznost-obecne]
=== OBECNĚ

. Tato pravidla je třeba číst ve spojitosti s částí <<#obecna-pravidla>>, Obecná pravidla.

. Soutěže v lezení na obtížnost se konají na účelově vyrobených umělých stěnách s minimální výškou 10 metrů, které dovolují postavit cesty s minimální délkou 12 metrů a minimální šířkou každé cesty 3 metry. Hlavní rozhodčí může po úvaze povolit šířku menší než 3 metry na omezeném úseku cesty.

. Všechny soutěže v lezení na obtížnost se lezou se spodním jištěním soutěžícího. U vybraných kategorií mládeže je povoleno lézt s horním jištěním – top-rope. Příslušné kategorie jsou uvedeny ve výjimkách z pravidel pro závody mládeže příslušných lig.

. Soutěž v lezení na obtížnost se obvykle sestává z:
.. kvalifikačního kola, které se musí odehrávat na dvou nestejných cestách. Obě cesty musí být přibližně stejného rázu a podobné technické obtížnosti. Cesty jsou přelézány po provedeném předlezení;
.. finále (v případě <<#mistrovstvi,Mistrovství>> i semifinále, všechny závody mládeže se lezou bez semifinále), které se odehrávají na jedné cestě a neprobíhá pro ně předlezení.

+
V případě nepředvídaných událostí může Hlavní rozhodčí zrušit jedno z kol. Je-li jedno kolo zrušeno, pak se výsledky z předchozího kola počítají rovněž jako výsledky zrušeného kola.
Pro kvalifikační kola platí odstavce <<#registrace>>, <<#pristup-do-soutezniho-prostoru>>.<<#pdsp-1>> a <<#pristup-do-soutezniho-prostoru>>.<<#pdsp-2>>.

. Návrh cest:
.. Každá cesta musí být postavena tak aby:
... se omezilo riziko zranění při pádu soutěžícího nebo jakékoliv třetí osoby. Nebo překážela jinému soutěžícímu.
... neobsahovala skoky směrem dolů

.. Hlavní rozhodčí může povolit že:
... lano bude zapnuté do jednoho nebo více jistících bodů a
... bude použít „chytač“ k zajištění dodatečné bezpečnosti v nižších částech stěny

+
ale pokud je to možné, návrh cesty by měl být udělaný tak, aby toto nebylo potřeba.

[#bezpecnost-a-jisteni]
=== BEZPEČNOST A JIŠTĚNÍ

. Hlavní rozhodčí
.. společně s Hlavním stavěčem musí zkontrolovat každou cestu před zahájením každého kola. Hlavní stavěč může označit, že jistící bod musí být z důvodu bezpečnosti zapnutý z příslušného chytu (<<#bezpecnostni-chyt,Bezpečnostní chyt>>) nebo dříve. V těchto případech příslušný chyt a jistící body musí být zřetelně označené modrým křížem a upozorněno na tuto skutečnost během prohlídky cesty.
.. rozhodne, zda má být lano vyměněno kdykoliv během soutěže

. Každý soutěžící musí mít nasazen úvazek. Hlavní rozhodčí nesmí povolit start soutěžícího, pokud má oprávněné důvody věřit, že úvazek soutěžícího je nebezpečný.

. Lezecké lano musí být pod kontrolou jednoho jističe, kterému pokud možno asistuje jeden pomocník. Každý jistič:

.. musí používat jen <<#manualni-jistitka,manuálně ovládané jistící pomůcky>> (zakázány jsou veškeré <<#blokovaci-jistitka,blokující jistící pomůcky>>). Veškeré jistící prostředky musí být schváleny Hlavním rozhodčím;
.. před každým pokusem musí zkontrolovat (nejlépe v přípravné zóně) že:
... úvazek soutěžícího je správně zajištěn
... lezecké lano musí být navázáno k úvazku soutěžícího za pomoci osmičkového uzlu zajištěného jedním uzlem navíc; 
... je lezecké lano stočené nebo jinak uspořádané tak, že je možné jej okamžitě a správně používat;

.. po celou dobu lezeckého pokusu soutěžícího na cestě musí jistič dávat neustále dobrý pozor na jeho postup a musí neustále povolovat lano o vhodnou délku, aby zajistil že:
... soutěžícího pohyby nebudou nijak omezovány příliš napjatým lanem;
... všechny pády budou zastaveny dynamickým a bezpečným způsobem 
... soutěžící je bezpečně spuštěn na zem. Je třeba dávat pozor, aby se soutěžící nedostal do kontaktu s žádným na zemi nebo jinde umístěným zařízením.
... když se soutěžící pokusí zapnout lano do bodu postupového jištění, musí mít k dispozici dostatečně volné lano, pokud se zapnutí nepodaří, průvěs musí být okamžitě dobrán;
... soutěžící nebude vystaven žádným nepřiměřeným pádům;
... je věnována velká pozornost tomu, aby nebyl padající nebo spouštěný soutěžící vystaven žádnému nebezpečí zranění, způsobenému hranou převisu nebo jiným prvkem lezecké stěny.

. Jakékoliv napnutí lana může být považováno za umělou pomoc nebo překážku pro soutěžícího a v takovém případě musí Hlavní rozhodčí oznámit technický incident.

. Zatímco si soutěžící odvazuje lano od svého úvazku, jistič musí stáhnout lano dolů tak rychle jak to jde bez toho, aby se nadměrně zatěžovaly expresky. Na zodpovědnosti jističe je zajistit, že soutěžící co nejrychleji uvolní lezeckou zónu.

[#startovni-listiny-obtiznost]
=== STARTOVNÍ LISTINY

. Startovní pořadí na první kvalifikační cestě bude náhodné. Startovní pořadí na druhé kvalifikační cestě bude stejné jako na té první, ale s posunem 50 %.

+
.Sudý počet závodníků
====
Při 20 soutěžících v dané kategorii, pak ten, který lezl jako 11. na první kvalifikační cestě, poleze na druhé cestě jako první.
====

+
.Lichý počet závodníků
====
Při 21 soutěžících v dané kategorii, pak ten, který lezl jako 11. na první kvalifikační cestě, poleze na druhé cestě jako první.
====

. Startovní pořadí v kolech následujících po kvalifikačním kole musí být opakem umístění v předchozím kole, např. nejlépe hodnocený soutěžící leze jako poslední. V případě společného umístění dvou a více soutěžících v předchozím kole bude jejich startovní pořadí v dalším kole určeno následovně:

.. pokud jsou soutěžící uvedeni v aktuálním průběžném rankingu, lezou v obráceném pořadí, než jsou v něm uvedeni;

.. pokud někteří soutěžící jsou a někteří nejsou v aktuálním průběžném rankingu, lezou nejprve ti, kteří v žebříčku nejsou;

.. pokud soutěžící v aktuálním průběžném rankingu nejsou uvedeni, startují v náhodném pořadí. Losování pořadí se provede pro každé kolo nově.

[#prubeh-souteze]
=== PRŮBĚH SOUTĚŽE
. Semifinálové a finálová kola v lezení na obtížnost se musí konat za dodržení <<#podminky-izolace,podmínek izolace>>. Soutěžící, kteří v těchto kolech startují se musí ohlásit v izolační zóně během kontroly docházky po oficiálním uzavření izolace. Soutěžící, kteří tak neučiní, nemohou v daném kole soutěžit.
. Musí se dodržet následující minimální časové mezery:
.. Odpočinek mezi dokončením pokusu na první cestě a nástupem pokusu na druhé cestě musí být minimálně 30 minut.  
.. Konají-li se dvě návazná kola po sobě (kvalifikace – semifinále, semifinále – finále u závodů nejvyšších soutěží, kvalifikace – finále u závodů 1. ligy), musí být minimálně 2 hodiny mezi dokončením 1. kola posledním závodníkem dané kategorie a uzavřením izolace této kategorie pro kolo další. V nezbytných případech může Hlavní rozhodčí rozhodnout o zkrácení této doby, doba mezi dokončením 1. kola posledním závodníkem dané kategorie a uzavřením izolace této kategorie pro kolo další nesmí klesnout pod 1 hodinu a informace o tomto zkrácení pak musí být veřejně vyhlášena a vyvěšena na oficiální tabuli nejpozději 15 minut před startem prvního závodníka v poslední cestě 1. kola.
.. Izolace by neměla být uzavřena dříve, než 1 hodinu před startem prvního závodníka. V případě více kategorií závodících na stejné cestě je myšlen první závodník první kategorie.
. Každý soutěžící musí zahájit pokus na jakékoliv cestě v pořadí definovaném oficiální startovní listinou. Start se nesmí přeplánovat, pokud soutěžící nemůže v daném čase odstartovat.
. Chyty na cestě je třeba čistit. Četnost čistění chytů určí Hlavní rozhodčí po poradě s Hlavním stavěčem. Maximální počet pokusů před každým čištěním je standardně 20 a nikdy nesmí překročit 22. Čistící úkony je v průběhu kola třeba rovnoměrně rozvrhnout. Četnost čištění je nutné soutěžícím oznámit v rámci technické instruktáže v izolaci a je třeba o něm informovat i na všech vydaných startovních listinách. 
. Před zahájením finálového kola musí proběhnout představení soutěžících v daném kole. Finálové kolo pro jakoukoliv jednu kategorii nesmí trvat déle než 90 minut.

[#prohlidka-cest]
=== PROHLÍDKA CEST
. Kvalifikační cesty musí být demonstrovány předlezci
.. pomocí videa přehrávaného ve smyčce v rámci <<#rozcvicovaci-zona, rozcvičovací zóny>>. Video musí být spuštěno nejpozději 60 minut před plánovaným startem daného kola; nebo
.. pokud video předlezení není možné, pak pomocí živého předlezení, které musí začít nejpozději 30 minut před pokusem prvního závodníka.

+
Je vhodné, aby cesty pro muže byly lezeny mužem, cesty pro ženy ženou.
. V souladu s částí <<#prohlidka-cesty>> obecných pravidel, soutěžící (jako skupina) mají povolenou prohlídku cest, které polezou za dodržení <<#podminky-izolace,podmínek izolace>>.

. Čas na společnou prohlídku cesty před semifinálovým nebo finálovým kolem je 6 minut.

.. Během této doby mohou soutěžící:
... se dotýkat prvního(ch) chytu(ů) za předpokladu, že obě chodidla zůstanou na zemi. 
... používat dalekohled
... dělat si poznámky a nákresy rukou

+
ale nesmí používat žádné nahrávací zařízení

+
.. Na konci doby určené k prohlídce cesty se soutěžící musejí neprodleně vrátit do izolace, nebo v případě několika prvních soutěžících na startovní listině, do přípravné zóny, když je k tomu vybídnou rozhodčí. Každé nepřiměřené zdržení může vyústit v obdržení žluté karty, jakákoliv další prodleva bude mít za následek diskvalifikaci v souladu s částí <<#disciplinarni-rizeni>>.

[#prubeh-lezeni]
=== PRŮBĚH LEZENÍ

. Stanovená délka doby lezení je 6 minut ve všech kolech.
. V momentě, kdy soutěžící vejde do soutěžní zóny u paty lezecké cesty, má 40 vteřin na to, aby nastoupil do cesty. Těchto 40 vteřin konečné prohlídky cesty není součástí celkového času vyhrazeného na přelezení cesty. Nezačne-li soutěžící po vypršení těchto 40 vteřin lézt, musí být ke startu okamžitě vyzván. Jakákoliv další prodleva bude mít za následek disciplinární postih v souladu s částí <<#disciplinarni-rizeni>>. 40 vteřin prohlídky cesty platí i v případě lezení kol, pro které neplatí <<#podminky-izolace,podmínky izolace>>.
. Každý pokus soutěžícího je považovaný za zahájený a čas se začne měřit v momentě, kdy obě chodidla soutěžícího opustí zem. Aby se předešlo pochybnostem, traťový rozhodčí určí, zda pokus začal nebo se jedná o úpravu postavení před startem.
. Soutěžící se v průběhu svého pokusu na cestě může ptát, kolik z času mu zbývá, přičemž Hlavní rozhodčí musí soutěžícího okamžitě informovat nebo někoho pověřit, aby soutěžícího informoval.
. Soutěžící v průběhu pokusu na cestě:
.. nesmí čistit chyty
.. soutěžící musí být stále v <<#legitimni-pozice,legitimní pozici>>.
.. Soutěžící musí zapínat expresky ve správném pořadí.
.. Zapínání expresky ze země je povoleno;
.. Soutěžícímu musí být umožněno vypnout lano z poslední zapnuté expresky a znovu ho do ní zapnout;
.. Pokud zapne soutěžící lano do karabiny v souladu s předchozími body, ale vytvoří tak „Z-klip“, musí jej soutěžící odstranit. Za tímto účelem je mu dovoleno odepnout a znovu zapnout (v případě nutnosti i slezením zpět) libovolnou z expresek v „Z-klipu“ zapojených. Po opravě musejí být všechna postupová jištění zapnuta.

. Pokus je považovaný za ukončený:
.. pokud bylo lano zapnuto z regulérní polohy do poslední expresky. V případě cesty lezené top-rope (mládež), je nutné dosáhnout posledního chytu oběma rukama. Tento chyt musí být jasně označen a musí na něj být upozorněno při předlezení.
.. spadnul
.. pokus byl ukončen Hlavním rozhodčím

. Hlavní rozhodčí musí ukončit pokus soutěžícího jestliže: 
.. má-li za to, že další postup na trati by byl nebezpečný
.. soutěžící
... překročil určený časový limit pro danou cestu 
... vrátil se zpět na zem po zahájení pokusu na cestě 
... využije jakoukoliv umělou pomůcku neuvedenou v pravidlech a neschválenou Hlavním rozhodčím.

. Hlavní rozhodčí může ukončit pokus soutěžícího jestliže:
.. soutěžící již není v legitimní pozici, nebo
.. nastal technický incident

. Za neuposlechnutí pokynu Hlavního rozhodčího ohledně ukončení pokusu bude soutěžící vystaven disciplinárnímu postihu v souladu s článkem <<#disciplinarni-rizeni>>.

[#hodnoceni-obtiznost]
=== HODNOCENÍ

. Nákres cesty musí být připravený Hlavním stavěčem za konzultace s Hlavním rozhodčím před startem každého kola soutěže. U semifinálových kol a finálových kol může být nákres cesty dán k dispozici <<#manazer-tymu,vedoucímu týmu>>, ale ne dříve než po skončení prohlídky příslušné cesty a po té co opustil <<#izolacni-zona,Izolační zónu>>.

. Každá cesta je posuzována alespoň jedním rozhodčím, kterému může asistovat osoba, která zapisuje každému soutěžícímu
.. lezecký čas, který se měří na sekundy (zaokrouhleno dolů)
.. dosažený výkon
. Pokud soutěžící během pokusu zůstal v <<#legitimni-pozice,legitimní pozici>> jeho výkon bude 
.. „TOP“ , pokud soutěžící zapnul poslední jistící bod během časového limitu pro lezení nebo
.. hodnota posledního chytu, definovaná v nákresu cesty, který byl soutěžícím <<#kontrolovat,držený>> nebo <<#pouzit,použitý>> předtím než:
... spadnul, nebo
... jeho pokus byl ukončený
. Pokud soutěžící nezůstal v <<#legitimni-pozice,legitimní pozici>> během jeho pokusu. Bude soutěžícímu zaznamenána hodnota chytu z nákresu, na kterém soutěžící byl ještě v legitimní pozici.

. Započítávají se pouze chyty dosažené rukama.  U chytu, který je <<#pouzit,použitý>> bude započítána hodnota tohoto chytu se znaménkem (+). Toto hodnocení je lepší než <<#kontrolovat,držení>> stejného chytu.

. Hodnocení pokusu soutěžícího bude pozastaveno na posledním chytu v nákresu, který Hlavní stavěč považuje za poslední, ze kterého je možné zapnout nezapnutou expresku a soutěžící tento chyt drží nebo jej mine. A to až do okamžiku, kdy je tato expreska zapnuta.

. Pokud soutěžící <<#pouzit,použije>> nebo <<#kontrolovat,drží chyt>>, který není v nákresu cesty, tak Hlavní rozhodčí spolu s Hlavním stavěčem přiřadí tomuto chytu bodovou hodnotu. Aby se předešlo pochybnostem, tato hodnota může být stejná jako již existující jiný chyt nebo nová.

. Chyt musí být jako takový definován Hlavním stavěčem před začátkem soutěžního kola a musí být zakreslen na nákresu cesty používaném traťovými rozhodčími k hodnocení nebo musí být při soutěži alespoň jedním soutěžícím úspěšně použit k postupu. Každému chytu je přiřazena bodová hodnota, definovaná vzestupnou číselnou řadou hodnot přiřazených jednotlivým chytům v linii cesty od nástupního chytu do posledního chytu v cestě.

. To, zda závodníci tečují či netečují následující chyt v linii cesty, není pro hodnocení znaménkem (+) podstatné.

[#poradi-po-kazdem-kole-obtiznost]
=== POŘADÍ PO KAŽDÉM KOLE

. Po každém kole soutěže jsou soutěžící seřazení podle hodnocení v souladu s částí <<#hodnoceni-obtiznost>> v pořadí:
.. soutěžící, kteří mají hodnocení TOP
.. ostatní soutěžící sestupně podle dosaženého výkonu
. Nastane-li na nějaké pozici remíza, vezmou se v úvahu výsledky soutěžících z předchozího kola (zpětné hodnocení).
. Celkové pořadí v kvalifikaci se počítá jako geometrický průměr následujícím způsobem:
+
stem:[PT = \sqrt{r_{1} \cdot r_{2}}]
+
Kde: stem:[PT] = celkové body
+
stem:[r_{1}] = umístění na kvalifikační cestě 1
stem:[r_{2}] = umístění na kvalifikační cestě 2.
+
Nižší celkové body znamenají lepší skóre. Pro každou cestu platí následující: v případě remízy mezi dvěma nebo více soutěžícími, umístění každého z nich bude aritmetickým průměrem umístění všech remízujících. Například, je-li na 1. místě 6 remízujících soutěžících, pak průměrné bodové umístění bude 3,5 stem:[(1 + 2 + 3 + 4 + 5 + 6 = 21 \div 6 = 3.5) ] nebo jsou-li na 2. místě 4 remízující, bude průměrné bodové umístění každého z nich 3,5 stem:[(2 + 3 + 4 + 5 = 14 \div 4 = 3.5)]. Při hodnocení je nutné počítat se všemi desetinnými místy, ale v oficiální výsledkové listině se uvedou pouze dvě.

. Jestliže soutěžící z jakéhokoliv důvodu nenastoupí do jedné z cest v kvalifikačním kole, bude tomuto soutěžícímu za cestu, kterou nenastoupil, přiřazeno umístění následující za posledním umístěným soutěžícím. Nenastoupí-li soutěžící na žádnou z cest, nebude hodnocen a výkon bude označen <<#dns,DNS>> nebo jinou případnou <<#irm,IRM>>.
. Nastane-li remíza ve finálovém kole poté, co bylo aplikováno zpětné hodnocení, rozhoduje o konečném umístění soutěžících čas dosažený ve finálovém kole tak, že nižší dosažený čas znamená lepší umístění. Pro tento účel musí být čas závodníků ve finále měřen oficiálním časoměřičem určeným Hlavním rozhodčím a tento čas bude zapsán do výsledkové listiny zaokrouhlený na sekundy směrem dolů. Čas je měřen od zahájení pokusu závodníka v cestě do jeho ukončení:
.. zapnutím poslední expresky (dosažením topu),
.. pádem,
.. porušením pravidel, znamenajícím ukončení pokusu v cestě (nepovolená pozice, zapnutí expresek v nesprávném pořadí, překročení časového limitu, využití nepovolených částí stěny k lezení atd.).

Pokud dosáhnou remizující závodníci ve finálovém kole po uplatnění zpětného hodnocení i shodného času, budou hodnoceni na stejném místě. Nekonají se již tedy žádná superfinále.

Vzhledem k zavedení času jako jednoho z rozhodujících kritérií ve finále je povinností pořadatele zajistit alespoň pro finálové pokusy kameru a finále všech závodníků zaznamenat pro možnost eventuálních protestů proti času.

[#stanoveny-pocet-soutezicich-na-kazde-kolo-obtiznost]
=== STANOVENÝ POČET SOUTĚŽÍCÍCH NA KAŽDÉ KOLO

. Část <<#stanoveny-pocet-soutezicich-na-kazde-kolo-obtiznost>> je třeba číst ve spojení s výše popsanou částí <<#poradi-po-kazdem-kole-obtiznost>>, tedy dříve, než aplikujeme část <<#stanoveny-pocet-soutezicich-na-kazde-kolo-obtiznost>>, je třeba sestavit pořadí.
. Při závodech nejvyšších soutěží je počet soutěžících kvalifikujících se pro semifinále 26 a pro finále 8 soutěžících. V případě, že počet soutěžících, kteří nastoupí do kvalifikace je nižší než 26, může Hlavní rozhodčí rozhodnout o zrušení semifinále a podle výsledků z kvalifikace postoupí rovnou do finále 8 soutěžících. Rozhodnutí o zrušení semifinále musí Hlavní rozhodčí oznámit všem soutěžícím dané kategorie před zahájením kvalifikace.
. U ligových závodů všech úrovní se automaticky vynechává semifinále a do finále postupuje 8 soutěžících.
. Stanovená kvóta bude naplněna soutěžícími s nejlepším umístěním z předešlého kola.
. Je-li stanovená kvóta přesažena v důsledku remízy soutěžících, pak se do dalšího kola soutěže kvalifikují všichni remízující soutěžící.

[#technicke-incidenty-obtiznost]
=== TECHNICKÉ INCIDENTY

. [[ti-obtiznost-1,{counter:ti-o:1}]]Za technický incident v soutěžích v lezení na obtížnost považujeme:
.. Zlomený nebo uvolněný chyt;
.. Nesprávně umístěná expreska nebo karabina;
.. Napnuté lano, které soutěžícímu buď pomáhá, nebo brání;
.. Jakákoliv jiná událost, která pro soutěžícího vyústí ve znevýhodnění nebo v nespravedlivé zvýhodnění a kterou soutěžící svým počínáním nezpůsobil.
. [[ti-obtiznost-2,{counter:ti-o}]]Jestliže soutěžící spadne a ohlásí, že za pád může technický incident, pak je okamžitě odveden do speciální izolace, kde musí vyčkat na rozhodnutí o vyšetření proklamovaného technického incidentu.
. [[ti-obtiznost-3,{counter:ti-o}]]V případě uznaného technického incidentu je soutěžícímu dán odpočinkový čas ve speciální izolaci s přístupem k rozcvičovacímu vybavení, přičemž během této doby nesmí soutěžící komunikovat s nikým jiným než se soutěžními činiteli ČHS a s organizátory.
+
Odpočinkový čas soutěžícího před dalším pokusem je přibližně 1 minuta za každý chyt dosažený v cestě, než došlo k technickému incidentu. Soutěžící, kterého se to týká, má právo na maximální čas na zotavení 20 minut. V závislosti na požadavcích soutěžícího ohledně odpočinkového času v rámci maximálního limitu pak Hlavní rozhodčí rozhodne o tom, kdy bude následující pokus soutěžícího zařazen. Všichni soutěžící, kterých se to týká, musejí být o tomto zařazení informováni.
+
V případě finálového soutěžního kola nesmí odpočinkový čas přesáhnout 20 minut od chvíle, kdy poslední soutěžící ukončil svůj pokus.
+
V případě, že by byl nějaký nový pokus zařazen v jakémkoliv kole soutěže za posledního soutěžícího a že soutěžící, který utrpěl technický incident, se v tomto kole již umístil jako první, nebude mu nový pokus povolen.
. Po dokončení opakovaného pokusu na cestě se soutěžícímu započítává nejlepší z jeho pokusů.

[#protesty-obtiznost]
=== PROTESTY
. Soutěžící nebo jeho trenér může proti rozhodnutí o ukončení pokusu podat okamžitý protest. Je-li takový protest podán, bude soutěžící odveden do speciální izolace. Protest je třeba podrobit postupu popsanému v části <<#protesty,protesty>> a odvolací komise se protestu musí věnovat, co nejdříve to okolnosti dovolí. Je-li protest uznán, má soutěžící právo na nový pokus. Soutěžícímu je třeba umožnit odpočinek za podobných podmínek jako v článku <<#technicke-incidenty-obtiznost>>.<<#ti-obtiznost-3>> hovořícím o zotavení se soutěžících po technickém incidentu. Po dokončení nového pokusu na cestě se soutěžícímu započítává nejlepší z jeho pokusů.

[#pouziti-videozaznamu-obtiznost]
=== POUŽITÍ VIDEOZÁZNAMU

. Má-li Hlavní rozhodčí za to, že je potřebné prohlédnout si videozáznam pokusu soutěžícího na cestě za účelem zhodnocení jeho výkonu, musí nejdříve soutěžícího ve shodě s pravidly nechat dokončit daný pokus. Jakmile soutěžící svůj pokus ukončí, musí ho Hlavní rozhodčí informovat, že jeho hodnocení v daném kole soutěže bude podléhat prozkoumání videozáznamu. Potvrzení hodnocení musí být provedeno co nejdříve.
. Oficiální videozáznam mohou používat rozhodčí pro potvrzení pravidel o držení/tečování v rámci hodnocení a umístění soutěžících na konci každého kola.
