[#protesty]
== PROTESTY

[#obecne-protesty]
=== OBECNĚ

. [[op-1,{counter:op}.]]Všechny písemné a ústní protesty a oficiální reakce se musejí odehrávat v češtině.
. [[op-2,{counter:op}.]]Písemný protest musí být na https://www.horosvaz.cz/res/archive/309/052084.pdf?seek=1577116013[formuláři ČHS] nebo na papíru obsahující stejné informace.
. [[op-3,{counter:op}.]]Protest může být uznán pouze v případě, pokud jiné body těchto pravidel neurčují jinak:
.. je-li spojen se zaplacením oficiálního protestného.
.. je podepsaný zástupcem soutěžícího (vedoucí týmu) nebo soutěžícím, pokud vedoucí týmu není přítomen
.. obsahuje konkrétní článek pravidel na jehož základě je protest podán a jméno soutěžícího nebo skupiny soutěžících, na které se protest vztahuje
. Bez ohledu na <<#obecne-protesty>>.<<op-3>> může odvolací porota rozhodnou o neplatnosti jakéhokoliv protestu
.. byl podán mimo definované časové intervaly
.. protest je založen na skutečnosti, která neodpovídá žádnému článku pravidel
.. odvolací porota se shodne, že protest není platný
. Po přijetí protestu nejprve odvolací porota vyhodnotí příslušný protest, zda je:
.. *neplatný* – v tomto případě je formulář s protestem vrácený a neplatí se poplatek za protest. Formulář je zároveň takto i označen
.. *platný* – v tomto případě se odvolací porota bude protestem zabývat

[#soutezeni-odvolaci-porota]
=== SOUTĚŽNÍ ODVOLACÍ POROTA

. V případě písemného nebo ústního protestu v souladu s článkem <<#protesty>> musí Hlavní rozhodčí shromáždit Odvolací porotu.
. Členy Odvolací poroty budou Hlavní rozhodčí, Delegát ČHS a Hlavní stavěč. V případě, že byl Hlavní rozhodčí původcem rozhodnutí, které protest vyvolalo, nastoupí na jeho místo v Odvolací porotě Ředitel závodu (pozn. pokud na závod není jmenován delegát ČHS, zůstává Hlavní rozhodčí členem Odvolací poroty na základě odstavce <<#oficialni-soutezni-cinitele>>.<<#td,1.b.>>.
. Pokud jsou dostupné důkazy a materiály neprůkazné nebo nemůže-li se Odvolací porota jednohlasně shodnout na posouzení protestu, pak platí původní rozhodnutí. Protest v tomto případě bude označen  „*nerozhodnutelný*“ a neplatí se poplatek za protest.
. Rozhodnout je třeba tak rychle, jak to okolnosti dovolí. V případě písemných protestů musí být písemné rozhodnutí Odvolací poroty předáno Hlavním rozhodčím osobě, která oficiálně protest podala nebo, v případě protestu podle níže zmíněného článku <<#protest-proti-vysledkum>>.<<#ppv-3b,3.b.>>, je třeba informovat vedoucího týmu a/nebo soutěžícího.

[#protesty-proti-bezpecnosti]
=== PROTESTY PROTI BEZPEČNOSTI
. Bez ohledu na jakékoliv jiné ustanovení těchto pravidel lze podat protest, pokud je možné, že existuje nějaké bezpečnostní riziko. Takový protest musí být:
.. podaný písemně a neplatí se poplatek za protest
.. podepsaný třemi (3) různými osobami z <<#oficialni-doprovod,oficiálního doprovodu týmu>>, každá z jiného týmu

+
a odvolací porota musí bez odkladu rozhodnout a aplikovat opatření vedoucí k odstranění tohoto identifikovaného rizika.

[#protest-proti-rozhodnuti]
=== PROTESTY PROTI ROZHODNUTÍ, KTERÉ SE TÝKÁ UKONČENÍ POKUSU SOUTĚŽÍCÍHO

. Jedná-li se o protest týkající se pokusu soutěžícího, je třeba protest podat Hlavnímu rozhodčímu, který okamžitě zahájí potřebné kroky v souladu s výše zmíněným postupem.
. Postižený soutěžící může tento protest podat slovně a neplatí poplatek. Pokud takový protest podává zástupce daného soutěžícího, pak jej musí podat písemně. Protest musí být podán do zahájení pokusu dalšího soutěžícího. 
. V boulderingu musí být podán protest:
.. v případě kola lezeného za dodržení <<#podminky-izolace,podmínek izolace>> <<#bouldering-klasicky-format,klasickým formátem>> do konce následující časového limitu pro výměnu závodníků.
.. v případě finálového kola lezeného <<#bouldering-format-sp,formátem SP>>, před zahájením pokusů následujícího závodníka.

+
V každém případě se soutěžící, kterého se protest týká, řídí pokyny hlavního rozhodčího. Aby se předešlo pochybnostem, kterýkoliv soutěžící, který opustí <<#soutezni-prostor,soutěžní prostor>> před rozhodnutím o protestu nebude mít možnost vykonat případné další pokusy.

. Na soutěžícího se do posouzení protestu nahlíží jako na závodníka postiženého technickým incidentem. 

[#protest-proti-vysledkum]
=== PROTESTY PROTI UVEŘEJNĚNÝM VÝSLEDKŮM

. [[ppv-1]]Protest proti umístění soutěžícího po skončení jakéhokoliv kola soutěže poté, co byly vyhlášeny oficiální výsledky umístění, je nutné provést nejpozději v čase 5 minut od vyhlášení umístění. Protest je možné vznést pouze po vyhlášení oficiálních výsledků po každém kole soutěže. Vedoucí týmu musí protest podat písemně Hlavnímu rozhodčímu, v případě nepřítomnosti vedoucího týmu tak učiní soutěžící. Odvolací porota musí zajistit, že všichni soutěžící, jejichž výsledek je zhoršen v důsledku protestu, jsou informováni.
. Soutěže v lezení na obtížnost
.. pokud se protest týká výkonu soutěžícího na konkrétním chytu, pak odvolací porota musí shlédnout výkony všech soutěžících, kteří byli hodnoceni, že daný chyt drželi nebo použili k postupu.
. Soutěže v lezení na rychlost:
.. V případě protestu proti uveřejněným výsledkům soutěžícího je třeba protest podat v souladu s výše zmíněným článkem <<#protest-proti-vysledkum>>.<<#ppv-1,1>>.
.. [[ppv-3b]]V případě protestu v průběhu vyřazovacího kola, je třeba protest podat ihned po ohlášení výsledku soutěžícího v daném vyřazovacím kole. Další vyřazovací kolo soutěže nesmí začít, dokud hlavní rozhodčí o protestu nerozhodne. Pokud jde o tyto protesty, neplatí se žádný poplatek.
. Hlavní rozhodčí označí příslušné výsledky jako „Pod protestem“, vyznačí, kterých konkrétních výsledků se protest týká, a zajistí, aby pořadatel vyhlásil, že výsledky jsou pod protestem.

[#dusledky-protestu]
=== DŮSLEDKY PROTESTU

. Jakékoliv formální rozhodnutí odvolací poroty je konečné a nepodléhá dalšímu protestu.

[#poplatky-za-protesty]
=== POPLATKY ZA PROTESTY

. Protestné ve výši 500 Kč musí být uhrazeno Hlavnímu rozhodčímu současně s podáním protestu.
. Je-li protest uznán protestné se vrací. Není-li protest uznán, protestné se nevrací.
