[#antidoping]
== ANTIDOPING

=== PŘIJETÍ

. ČHS přijal světová antidopingová pravidla.

=== POUŽITÍ

. Antidopingová pravidla se vztahují na všechny soutěže pořádané pod záštitou ČHS. Jakákoliv osoba – jako sportovec, trenér, soutěžní činitel, člen lékařského nebo ošetřovatelského personálu - která se přihlásí, připravuje se nebo se účastní těchto soutěží, je chápána jako někdo, kdo souhlasil respektováním a podřízením se antidopingovým pravidlům.

=== PŘÍSLUŠNÉ ORGÁNY V RÁMCI ČHS

. Příslušné orgány v rámci ČHS, které se zabývají prosazováním antidopingových pravidel v lezeckých soutěžích – které zahrnují lezení na obtížnost, bouldering, lezení na rychlost a kombinaci – jsou Lékařská a Disciplinární komise ČHS.

=== PŘESTUPKY A SANKCE

. S dopingovými přestupky bude nakládáno ve shodě s Antidopingovou politikou Světové antidopingové asociace a s Disciplinárním řádem ČHS.
. Při jakémkoli porušení antidopingových pravidel ztrácí závodník právo startu v závodech organizovaných ČHS, zároveň je závodník (případně jeho zákonný zástupce) v takovém případě povinen uhradit ČHS způsobenou škodu v plné výši včetně škody způsobené ztrátou státních dotací na základě dopingového nálezu člena sportovního svazu.